# Generated by Django 3.2 on 2021-05-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recorder',
            name='phone',
        ),
    ]
