# Generated by Django 3.1.6 on 2021-03-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='telephone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
