# Generated by Django 3.1.6 on 2021-04-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_harvestrecord_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='cooperativename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.cooperative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regfarmer',
            name='cooperativename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.cooperative'),
            preserve_default=False,
        ),
    ]
