# Generated by Django 3.2 on 2021-05-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_recorder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilecooperative',
            name='farmers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.allfarmers'),
        ),
    ]
