# Generated by Django 3.1.6 on 2021-04-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210402_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='username',
            new_name='Email',
        ),
    ]
