# Generated by Django 3.1.6 on 2021-04-12 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20210412_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorder',
            name='user',
        ),
        migrations.AlterField(
            model_name='recorder',
            name='cooperativename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
