# Generated by Django 3.1.6 on 2021-04-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210412_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorder',
            name='cooperativename',
        ),
        migrations.RemoveField(
            model_name='regfarmer',
            name='cooperativename',
        ),
    ]
