# Generated by Django 3.2 on 2021-05-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210515_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='recorder',
            field=models.CharField(max_length=255),
        ),
    ]
