# Generated by Django 3.1.6 on 2021-04-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210414_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperative',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='harvestrecord',
            old_name='code',
            new_name='farmercode',
        ),
        migrations.AddField(
            model_name='cooperative',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
