# Generated by Django 3.2 on 2021-05-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_harvestrecord_regcooperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.recorder'),
        ),
    ]
