# Generated by Django 3.1.6 on 2021-04-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210415_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='Email',
            new_name='email',
        ),
    ]
