# Generated by Django 3.2 on 2021-05-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_harvestrecord_recorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestrecord',
            name='recorder',
        ),
    ]
