# Generated by Django 3.1.6 on 2021-04-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210419_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allfarmers',
            old_name='code',
            new_name='farmercode',
        ),
    ]
