# Generated by Django 3.2 on 2021-05-20 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_remove_harvestrecord_regcooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='recorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.recorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='regCooperative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
