# Generated by Django 3.2 on 2021-05-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210520_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfarmers',
            name='country',
        ),
        migrations.RemoveField(
            model_name='allfarmers',
            name='dateofbirth',
        ),
    ]
