# Generated by Django 3.2 on 2021-05-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210521_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='email',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='recorder',
            old_name='password',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='recorder',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='recorder',
            name='username',
        ),
    ]
