# Generated by Django 3.2 on 2021-05-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20210526_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='regCooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cooperative'),
        ),
    ]
