# Generated by Django 3.2 on 2021-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_harvestrecord_regcooperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='recorder',
            field=models.CharField(max_length=255),
        ),
    ]
