# Generated by Django 3.2 on 2021-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_harvestrecord_recorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorder',
            name='regCooperative',
            field=models.CharField(max_length=255),
        ),
    ]
