# Generated by Django 3.2 on 2021-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20210527_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='recorder',
            field=models.CharField(max_length=255),
        ),
    ]
