# Generated by Django 3.2 on 2021-05-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_harvestrecord_recorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Quantity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
