# Generated by Django 3.2 on 2021-06-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_harvestrecord_recorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='record',
            new_name='telephone',
        ),
    ]
